server:
  port: 8090
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/wms
    username: wms
    password: wms

---

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://kokoserver.me:5432/wms
    username: wms
    password: wms